### ISSUE TITLE
Implement node-hid support

### ISSUE THREAD

**Issue by gre** [LedgerHQ/ledger-repl#3]
- Proxied from renderer side. meaning we want to create our transport on the renderer side but the code run in main thread, so we need some sort of communication to open/exchange/close over the threads (hopefully not too hard with carlo functions).
- Make sure to use @ledgerhq/node-hid-no-events & make sure that netlify is happy about this dependency. if not, we'll have to figure out something for netlify to still work out.

**Comment by meriadec** [comment]
will try something on this. first difficulty I see is carlo out-of-the box just provide exposing function to the renderer (single promise result) while we need event based logic

**Comment by gre** [comment]
@meriadec  carlo paradigm is fine, in fact it's perfect because it's minimal. You can expose from main to renderer a ledgerTransport function. From renderer you could imagine using it like this:

```
ledgerTransport("exchange", apdu) => Promise<apdu raw response>
ledgerTransport("open") => Promise<void>
ledgerTransport("close") => Promise<void>
```

On main side, implementing this function is just about keeping a singleton transport in a global variable and just calling the relevant method (open, close, exchange).

what else do you need in fact? The tricky part is obviously to have some protection in not calling twice open() if the previous one have not finished / some general lock protection around it from renderer side.

As said in initial message, we would use node-hid-no-events, which **does not** offer usb events. So listen() and list() typically always returns `[""]`, optimistically saying "yeah don't worry there is a device :trollface:".

https://github.com/LedgerHQ/ledgerjs/tree/master/packages/hw-transport-mocker/src can be an example in how minimal a transport can be. on renderer side, you can just create a transport that have a close() and exchange().. especially that with live-common you just need to provide a open function: https://github.com/LedgerHQ/ledger-repl/blob/master/src/renderer/live-common-setup.js#L39-L47

**Comment by gre** [comment]
also, for errors, you can use serialization/deserialization of `@ledgerhq/errors` ^^

> one side note is that i'm not sure how you can forward the "disconnect" event, but you can ignore it for now because it's not even implementing in node-hid transport as we're already in trouble properly detecting this.

**Comment by meriadec** [comment]
Ok :+1: thanks for pointing this :) I was also considering [`rpc`](https://github.com/GoogleChromeLabs/carlo/blob/master/rpc/rpc.md) handlers but it may be overkill
